"""Initial migration with todos table

Revision ID: 837db9457925
Revises: 
Create Date: 2025-09-22 00:11:00.778507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837db9457925'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todos',
    sa.Column('id', sa.Integer(), nullable=False, comment='主キー'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='タイトル（必須、最大200文字）'),
    sa.Column('description', sa.Text(), nullable=True, comment='説明（任意、最大1000文字）'),
    sa.Column('completed', sa.Boolean(), nullable=False, comment='完了状態（デフォルト: False）'),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=True, comment='完了予定日'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='作成日時（自動設定）'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新日時（自動更新）'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_todos_completed', 'todos', ['completed'], unique=False)
    op.create_index('idx_todos_completed_created', 'todos', ['completed', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_todos_created_at', 'todos', ['created_at'], unique=False)
    op.create_index('idx_todos_end_date', 'todos', ['end_date'], unique=False)
    op.create_index('idx_todos_incomplete_end_date', 'todos', ['completed', 'end_date'], unique=False)
    op.create_index('idx_todos_incomplete_only', 'todos', [sa.text('created_at DESC')], unique=False, postgresql_where=sa.text('completed IS false'))
    op.create_index(op.f('ix_todos_id'), 'todos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todos_id'), table_name='todos')
    op.drop_index('idx_todos_incomplete_only', table_name='todos', postgresql_where=sa.text('completed IS false'))
    op.drop_index('idx_todos_incomplete_end_date', table_name='todos')
    op.drop_index('idx_todos_end_date', table_name='todos')
    op.drop_index('idx_todos_created_at', table_name='todos')
    op.drop_index('idx_todos_completed_created', table_name='todos')
    op.drop_index('idx_todos_completed', table_name='todos')
    op.drop_table('todos')
    # ### end Alembic commands ###